background {
    monitor =
    path = ~/Pictures/Wallpapers/chained-firekeeper.png
    blur_passes = 3
    blur_size = 6
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(94e2d5)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    dots_center = true
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(cdd6f4ff)
    font_size = 64
    font_family = FiraCode Nerd Font
    position = 0, 200
    halign = center
    valign = center
}
